
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 04 13:27:40 CET 2019
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int IDF = 15;
  public static final int EGAL = 7;
  public static final int OU = 25;
  public static final int CSTENTIERE = 16;
  public static final int PLUS = 26;
  public static final int SUP = 20;
  public static final int LIRE = 6;
  public static final int ECRIRE = 9;
  public static final int CSTBOOLEAN = 18;
  public static final int ALORS = 11;
  public static final int NON = 14;
  public static final int INF = 21;
  public static final int MOINS = 19;
  public static final int POINTVIRGULE = 5;
  public static final int SINON = 12;
  public static final int TYPE = 17;
  public static final int MULT = 27;
  public static final int ENTIER = 8;
  public static final int EOF = 0;
  public static final int EGALEGAL = 22;
  public static final int DIV = 28;
  public static final int ET = 24;
  public static final int SI = 10;
  public static final int error = 1;
  public static final int DIFF = 23;
  public static final int DEBUT = 3;
  public static final int FINSI = 13;
  public static final int FIN = 4;
  public static final int PROGRAMME = 2;
}

