
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 30 09:55:19 CET 2019
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FONCTION = 35;
  public static final int TANTQUE = 32;
  public static final int CROFER = 18;
  public static final int MULT = 30;
  public static final int EGAL = 7;
  public static final int REPETER = 33;
  public static final int SI = 10;
  public static final int VIRGULE = 37;
  public static final int FIN = 4;
  public static final int LIRE = 6;
  public static final int LONGUEUR = 39;
  public static final int OU = 28;
  public static final int CSTBOOLEAN = 21;
  public static final int INF = 24;
  public static final int NON = 14;
  public static final int PAROUV = 15;
  public static final int DIV = 31;
  public static final int EGALEGAL = 25;
  public static final int PLUS = 29;
  public static final int DEBUT = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RETOURNE = 36;
  public static final int MOINS = 22;
  public static final int ET = 27;
  public static final int SINON = 12;
  public static final int IDF = 19;
  public static final int ALORS = 11;
  public static final int PARFER = 16;
  public static final int POINT = 38;
  public static final int CROOUV = 17;
  public static final int CSTENTIERE = 20;
  public static final int PROGRAMME = 2;
  public static final int POINTVIRGULE = 5;
  public static final int FINTANTQUE = 34;
  public static final int SUP = 23;
  public static final int DIFF = 26;
  public static final int ENTIER = 8;
  public static final int FINSI = 13;
  public static final int ECRIRE = 9;
}

